#!/usr/bin/env python3
"""
Generate a fully functional Python login crawler for a whitelisted target.
Reverses login mechanisms (including JS encryption) and outputs a standalone script.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from urllib.parse import urljoin, urlparse
from datetime import datetime, timezone

TEMPLATE = '''#!/usr/bin/env python3
"""
Login Crawler for {target}
Generated by Reverse Flow - Authorized Penetration Testing Only
Generated UTC: {timestamp}
Target Whitelisted: Yes
robots.txt: Ignored (authorized testing)
"""
import argparse
import hashlib
import json
import time
import sys
from urllib.parse import urljoin, urlparse

try:
    import requests
    from bs4 import BeautifulSoup
except ImportError:
    print("[!] Please install requests and beautifulsoup4: pip install requests beautifulsoup4")
    sys.exit(1)

# ============================================================
# CONFIGURATION (Extracted from target analysis)
# ============================================================
BASE_URL = "{base_url}"
LOGIN_URL = "{login_url}"
USERNAME_FIELD = "{username_field}"
PASSWORD_FIELD = "{password_field}"
EXTRA_FIELDS = {extra_fields}
ENCRYPTION_TYPE = "{encryption_type}"
PUBLIC_KEY = "{public_key}"  # If RSA
STATIC_SALT = "{static_salt}"  # If salted hash

HEADERS = {{
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": BASE_URL,
}}

# ============================================================
# ENCRYPTION REVERSAL (Replicated from JavaScript)
# ============================================================

def encrypt_password(password: str) -> str:
    """Replicate client-side JS encryption logic."""
    # Example: MD5 hashing (replace with actual reversed logic)
    if ENCRYPTION_TYPE == "md5":
        return hashlib.md5(password.encode()).hexdigest()
    elif ENCRYPTION_TYPE == "sha256":
        return hashlib.sha256(password.encode()).hexdigest()
    elif ENCRYPTION_TYPE == "rsa":
        # Placeholder: Use pycryptodome if available
        # from Crypto.PublicKey import RSA
        # from Crypto.Cipher import PKCS1_v1_5
        # key = RSA.import_key(PUBLIC_KEY)
        # cipher = PKCS1_v1_5.new(key)
        # return cipher.encrypt(password.encode()).hex()
        return password  # TODO: Replace with actual RSA logic
    elif ENCRYPTION_TYPE == "plain":
        return password
    else:
        # Default to plain
        return password

def get_csrf_token(session: requests.Session, url: str) -> str:
    """Fetch CSRF token from login page."""
    resp = session.get(url, headers=HEADERS)
    soup = BeautifulSoup(resp.text, "html.parser")
    # Common CSRF field names: csrf_token, _token, authenticity_token
    for name in ["csrf_token", "_token", "authenticity_token", "csrfmiddlewaretoken"]:
        field = soup.find("input", {{"name": name}})
        if field and field.get("value"):
            return field["value"]
    return ""

# ============================================================
# LOGIN FUNCTION
# ============================================================

def login(username: str, password: str, session: requests.Session = None) -> requests.Session:
    """Authenticate and return a session."""
    if session is None:
        session = requests.Session()

    # Step 1: Get CSRF token (if required)
    csrf_token = get_csrf_token(session, BASE_URL)
    if csrf_token:
        print(f"[+] CSRF token obtained: {{csrf_token[:10]}}...")

    # Step 2: Prepare payload
    payload = {{
        USERNAME_FIELD: username,
        PASSWORD_FIELD: encrypt_password(password),
        **EXTRA_FIELDS,
    }}
    if csrf_token:
        payload["csrf_token"] = csrf_token

    # Step 3: Send login request
    print(f"[+] Sending login POST to {{LOGIN_URL}}")
    resp = session.post(LOGIN_URL, data=payload, headers=HEADERS, allow_redirects=True)

    # Step 4: Check success
    if resp.status_code == 200 and ("dashboard" in resp.url.lower() or "welcome" in resp.text.lower()):
        print("[+] Login successful!")
        return session
    elif resp.status_code == 302:
        print("[+] Redirect detected, following...")
        return session
    else:
        print(f"[-] Login failed. Status: {{resp.status_code}}")
        print(f"[-] Response snippet: {{resp.text[:200]}}")
        sys.exit(1)

# ============================================================
# CRAWLING FUNCTIONS
# ============================================================

def crawl(session: requests.Session, path: str) -> requests.Response:
    """Authenticated GET request."""
    url = urljoin(BASE_URL, path)
    resp = session.get(url, headers=HEADERS)
    time.sleep(1)  # Rate limiting
    return resp

# ============================================================
# MAIN
# ============================================================

def main():
    parser = argparse.ArgumentParser(description="Login crawler for {target}")
    parser.add_argument("--username", required=True, help="Username for login")
    parser.add_argument("--password", required=True, help="Password for login")
    parser.add_argument("--url", default=BASE_URL, help="Target URL to crawl after login")
    parser.add_argument("--output", "-o", help="Save response to file")
    args = parser.parse_args()

    print(f"[*] Target: {{BASE_URL}}")
    print(f"[*] Authenticating as {{args.username}}...")

    session = login(args.username, args.password)

    print(f"[*] Crawling: {{args.url}}")
    resp = crawl(session, args.url)

    print(f"[*] Response status: {{resp.status_code}}")
    if args.output:
        with open(args.output, "w") as f:
            f.write(resp.text)
        print(f"[+] Saved to {{args.output}}")
    else:
        print(resp.text[:500] + "...")

    return 0

if __name__ == "__main__":
    raise SystemExit(main())
'''

def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a login crawler Python script from target analysis")
    parser.add_argument("--target", required=True, help="Base target URL (e.g., https://example.com)")
    parser.add_argument("--login-url", help="Login endpoint (default: /login)")
    parser.add_argument("--username-field", default="username", help="Username field name")
    parser.add_argument("--password-field", default="password", help="Password field name")
    parser.add_argument("--encryption", choices=["plain", "md5", "sha256", "rsa", "custom"], default="plain", help="Password encryption type")
    parser.add_argument("--public-key", help="RSA public key (if encryption=rsa)")
    parser.add_argument("--static-salt", help="Static salt for hashing")
    parser.add_argument("--out", required=True, help="Output Python file path")
    parser.add_argument("--extra-fields", help='JSON object of extra form fields (e.g., {"csrf_token": ""} )')
    args = parser.parse_args()

    target = args.target.rstrip("/")
    login_url = urljoin(target, args.login_url or "/login")
    extra_fields = json.loads(args.extra_fields) if args.extra_fields else {}

    output = TEMPLATE.format(
        target=target,
        base_url=target,
        login_url=login_url,
        username_field=args.username_field,
        password_field=args.password_field,
        extra_fields=json.dumps(extra_fields),
        encryption_type=args.encryption,
        public_key=args.public_key or "",
        static_salt=args.static_salt or "",
        timestamp=datetime.now(timezone.utc).isoformat()
    )

    out_path = Path(args.out).expanduser().resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(output, encoding="utf-8")
    print(f"[+] Crawler generated: {out_path}")
    print("[*] Review and adjust the encryption logic if needed.")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
